CREATE TABLE USER(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_NAME VARCHAR(16) NOT NULL,
  USER_ID VARCHAR(10) NOT NULL UNIQUE,
  PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE STOCK_CATALOG(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  STOCK_NAME VARCHAR(64) NOT NULL ,
  TICKER VARCHAR(8) NOT NULL ,
  MARKET_PRICE BIGINT NOT NULL
);

CREATE TABLE FINANCIAL_PRODUCT(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_NAME VARCHAR(64) NOT NULL,
  BUY_PRICE BIGINT NOT NULL,
  MATURITY_PRICE BIGINT NOT NULL
);

